name: Pull Request Build
# For pull requests: builds and test
on:
  push:
    branches:
      - '!master'
  pull_request:
    branches:
      - master
jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: build and test
        run: ./gradlew assemble && ./gradlew check --info --stacktrace
